name: CI
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "**"
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash # https://github.com/beeware/briefcase/pull/912

jobs:
  install-briefcase:
    name: Install Briefcase
    runs-on: macos-latest
    steps:
    - name: Checkout .github repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: "3.10"

    - uses: actions/setup-node@v3.6.0

    - name: Install Briefcase
      uses: rmartin16/.github-beeware/.github/actions/install-briefcase@auth-implicit-token

  verify-apps:
    name: Build apps
    uses: rmartin16/.github-beeware/.github/workflows/app-build-verify.yml@auth-implicit-token
    with:
      python-version: ${{ matrix.python-version }}
      runner-os: windows-latest
      framework: ${{ matrix.framework }}
      target-platform: windows
      target-format: app
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]  #, "3.10", "3.9", "3.8"]
        framework: ["toga", "pyside2", "pyside6", "ppb"]
        exclude:
        # PySide2 doesn't publish a binary wheel that is compatible
        # with Python 3.11, and is unlikely to ever do so.
        - python-version: "3.11"
          framework: "pyside2"
