name: CI
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "**"
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash # https://github.com/beeware/briefcase/pull/912

jobs:
  verify-apps:
    name: Build apps
    uses: rmartin16/.github-beeware/.github/workflows/verify-app-build.yml@briefcase-from-pr-body
    with:
      python-version: ${{ matrix.python-version }}
      runner-os: windows-latest
      framework: ${{ matrix.framework }}
      target-platform: windows
      target-format: app
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        framework: ["toga", "pyside2", "pyside6", "ppb"]
        exclude:
        # PySide2 doesn't publish a binary wheel that is compatible
        # with Python 3.11, and is unlikely to ever do so.
        - python_version: "3.11"
          framework: "pyside2"
