name: Install Windows Store Python
description: Installs Python from the Windows Store

inputs:
  python-version:
    description: "Python version to install"
    default: "3.11"  # should default to the latest Python
    required: false

runs:
  using: composite
  steps:

    - name: Python Definitions
      id: python
      shell: powershell
      run: |
        switch ( "${{ inputs.python-version }}" ) {
          "3.11" {
            $StoreURL = "https://apps.microsoft.com/store/detail/python-311/9NRWMJP3717K"
            $ExeDir = Join-Path "$env:LOCALAPPDATA" "\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0"
            $ScriptsDir = Join-Path "$env:LOCALAPPDATA" "\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts"
          }
          "3.10" {
            $StoreURL = "https://apps.microsoft.com/store/detail/python-310/9PJPW5LDXLZ5"
            $ExeDir = Join-Path "$env:LOCALAPPDATA" "\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0"
            $ScriptsDir = Join-Path "$env:LOCALAPPDATA" "Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts"
          }
          "3.9" {
            $StoreURL = "https://apps.microsoft.com/store/detail/python-39/9P7QFQMJRFP7"
            $ExeDir = Join-Path "$env:LOCALAPPDATA" "\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0"
            $ScriptsDir = Join-Path "$env:LOCALAPPDATA" "Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts"
          }
          "3.8" {
            $StoreURL = "https://apps.microsoft.com/store/detail/python-38/9MSSZTT1N39L"
            $ExeDir = Join-Path "$env:LOCALAPPDATA" "\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0"
            $ScriptsDir = Join-Path "$env:LOCALAPPDATA" "\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts"
          }
          default {
            echo " >>> Python ${{ inputs.python-version }} is not supported <<<"
            exit 1
          }
        }

        echo "version=${{ inputs.python-version }}" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
        echo "store-url=$StoreURL" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
        echo "exe-dir=$ExeDir" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
        echo "scripts-dir=$ScriptsDir" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
        echo "appx-path=$(Join-Path "$env:TEMP" python-${{ inputs.python-version }}.appx)" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: Cache Python AppxBundle
      uses: actions/cache@v3.2.3
      with:
        path: ${{ steps.python.outputs.appx-path }}
        key: python-${{ steps.python.outputs.version }}-appx-bundle

    - name: Install Windows Store Python ${{ steps.python.outputs.version }}
      shell: powershell
      run: |
        if (-not (Test-Path -Path "${{ steps.python.outputs.appx-path }}" -PathType Leaf)) {
          # The Appx download URL must be resolved each time since the URL expires after a few hours
          echo "Downloading Python ${{ steps.python.outputs.version }}..."
          $WebResponse = Invoke-WebRequest -UseBasicParsing -Method 'POST' -Uri 'https://store.rg-adguard.net/api/GetFiles' -Body "type=url&url=${{ steps.python.outputs.store-url }}&ring=Retail" -ContentType 'application/x-www-form-urlencoded'
          $DownloadURL = ($WebResponse.Links | where {$_ -like '*.msix*'} | where {$_ -like '*_neutral_*' -or $_ -like "*_"+$env:PROCESSOR_ARCHITECTURE.Replace("AMD","X").Replace("IA","X")+"_*"} | Select-String -Pattern '(?<=a href=").+(?=" r)').matches.value

          echo "Appx download URL: $DownloadURL"
          if (($DownloadURL -eq $null) -or ((([uri]$DownloadURL).Host.split('.')[-2..-1] -join '.') -ne "microsoft.com")) {
            echo $WebResponse
            echo " >>> Download URL must resolve to microsoft.com. Aborting. <<< "
            exit 1
          }
          Invoke-WebRequest -Uri $DownloadURL -UseBasicParsing -OutFile ${{ steps.python.outputs.appx-path }}
        }

        echo "Installing Python ${{ steps.python.outputs.version }}..."
        Add-AppxPackage -Path ${{ steps.python.outputs.appx-path }}

        echo "Updating `$PATH..."
        echo "${{ steps.python.outputs.exe-dir }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "${{ steps.python.outputs.scripts-dir }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
